# Generated by Django 5.2.12 on 2026-03-08 16:52

import django.core.validators
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format (e.g. +27821234567)', regex=re.compile('^\\+[1-9]\\d{6,14}$'))])),
                ('role', models.CharField(choices=[('member', 'Member'), ('driver', 'Driver'), ('admin', 'Admin')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='approved', max_length=10)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('car_color', models.CharField(blank=True, default='', max_length=50)),
                ('car_plate', models.CharField(blank=True, default='', max_length=20)),
                ('car_type', models.CharField(blank=True, default='', max_length=50)),
                ('car_year', models.CharField(blank=True, default='', max_length=10)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_salt', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
